### ISSUE TITLE
Double clearing of task possibly leading to very hard to debug bugs

### ISSUE THREAD

**Issue by burnpanck** [pearu/pylibnidaqmx#60]
`Task.clear` does not check if the task actually has been cleared already. However, after `DAQmxClearTask` is called, the task handle is completely dead for DAQmx. Particularly, DAQmx might re-use the same handle (i.e. the pointer value) for another task. If clear on the original pylibnidaqmx `Task` object is called again, it actually clears the handle of **another** task. This is exacerbated by the fact that `Task.__del__` performs a clear, which can happen at a much later time than when the task is last used. I'll post a PR soon.

**Comment by hoechenberger** [comment]
Hello @burnpanck, please feel free to make a PR anytime if you have a fix for this issue :)
